name: build solution and run tests

on:
  push:
    branches: [master]
  pull_request:
    branches: ["master"]
env:
  AZURE_WEBAPP_NAME: bestSellerCaseBackend
  AZURE_RESOURCE_GROUP: BestSellerGroup
  AZURE_REGION: northeurope
  DOTNET_VERSION: '8.0'   
  
permissions:
  id-token: write
  contents: read
  
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      azurite:
        image: mcr.microsoft.com/azure-storage/azurite
        ports:
          - 10002:10002  # Table storage


    steps:       
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build (test)
      run: dotnet build --no-restore
      
    - name: Run test
      run: dotnet test

    - name: Build (release)
      run: dotnet build --configuration Release

    - name: Publish
      run: dotnet publish -c Release -o out

    - name: Upload DLL artifact
      uses: actions/upload-artifact@v4
      with:
        name: App
        path: out/**/*.dll

    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Register Microsoft.Web provider
      run: az provider register --namespace Microsoft.Web
    - name: Ensure Resource Group Exists
      run: |
        az group show --name ${{ env.AZURE_RESOURCE_GROUP }} || \
        az group create --name ${{ env.AZURE_RESOURCE_GROUP }} --location ${{ env.AZURE_REGION }}


    - name: Deploy ARM template
      run: |
        az deployment group create  \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --template-file arm.json \
          --parameters webAppName=${{ env.AZURE_WEBAPP_NAME }} \
                       location=${{ env.AZURE_REGION }} \
                       appServicePlanName=${{ env.AZURE_WEBAPP_NAME }}-plan
