name: build solution and run tests

on:
  push:
    branches: [master]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      azurite:
        image: mcr.microsoft.com/azure-storage/azurite
        ports:
          - 10002:10002  # Table storage
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build (test)
      run: dotnet build --no-restore
      
    - name: Run test
      run: dotnet test

    - name: Build (release)
      run: dotnet build --configuration Release

    - name: Publish
      run: dotnet publish -c Release -o out

    - name: Upload DLL artifact
      uses: actions/upload-artifact@v4
      with:
        name: App
        path: out/**/*.dll
