name: Build and deploy ASP.Net Core app to Azure Web App - bestSellerCaseBackend

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore        

      - name: Build with dotnet
        run: dotnet build --configuration Release
        
      - name: dotnet publish
        run: dotnet publish ./BestSellerCaseBackend/Backend.csproj -c Release -o ./publish_output
      
      - name: Zip published files
        run: zip -r release.zip ./publish_output
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write   # Required for requesting the JWT
      contents: read    # Required for actions/checkout

    steps:


      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_510FA65B0F7A47DFBDBBFC37B8BF7AD5 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4B47355A8C364528BBE4686A12877509 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AB50C1CC494345E1A26484D53EFF9BD5 }}

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: .
      
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bestSellerCaseBackend'
          slot-name: 'Production'
          package: release.zip





