name: Build and deploy ASP.Net Core app to Azure Web App - bestSellerCaseBackend

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore 

      - name: Build solution
        run: dotnet build  --configuration Release --no-restore


      - name: Publish web app
        run: dotnet publish ./BestSellerCaseBackend/Backend.csproj -c Release -o ./publish_output

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: ./publish_output
          

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: webapp
          path: ./webapp

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_96B7FAC72D7640D6B6B26B8F8A35011C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8961381B00154A07B144770CCA8EC925 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BC807FFB5205485E9B15F3446F2571AB }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bestSellerCaseBackend'
          slot-name: 'Production'
          package: ./webapp


