name: Build and deploy ASP.Net Core app to Azure Web App - bestSellerCaseBackend

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore BestSellerCaseBackend/BestSellerCaseBackend/backend.csproj

      - name: Build with dotnet
        run: dotnet build BestSellerCaseBackend/BestSellerCaseBackend/backend.csproj --configuration Release --no-restore

      - name: Publish with dotnet
        run: dotnet publish BestSellerCaseBackend/BestSellerCaseBackend/backend.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp --no-build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write   # Required for requesting the JWT
      contents: read    # Required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_510FA65B0F7A47DFBDBBFC37B8BF7AD5 }}
          tenant-id: ${{ secre

